image: python:3.6

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - pre-publish
  - publish

test:linter:
  stage: test
  script:
    - pip install tox
    - make lint

test:code-formatter:
  stage: test
  script:
    - pip install tox
    - make code-formatter-check

test:unit-tests:
  stage: test
  script:
    - pip install tox
    - make tests

test:coverage:
  stage: test
  only:
    - master
  script:
    - pip install tox
    - make coverage
  coverage: '/^TOTAL.+?(\S+\%)$/'

publish-docker:
  stage: pre-publish
  image: docker
  only:
    - /^release/.*$/
  before_script:
    - apk add python3-dev
    - python3 setup.py sdist
  script:
    - export VERSION_TAG=$(cat setup.py | grep version | head -1 | awk -F= '{ print $2 }' | sed 's/[",]//g' | tr -d "'")
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}
    - docker pull ${CI_REGISTRY_IMAGE}:${VERSION_TAG} && echo "Tag ${VERSION_TAG} already exists" && exit 1 || true
    - docker build -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${VERSION_TAG}  .
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${VERSION_TAG}
    - docker login -u hmajid2301 -p ${DOCKER_PASSWORD}
    - export IMAGE_NAME="hmajid2301/composerisation"
    - docker build -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${VERSION_TAG}  .
    - docker push ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:${VERSION_TAG}

publish-readme:hub:
  stage: pre-publish
  only:
    - /^release/.*$/
  image:
    name: registry.gitlab.com/hmajid2301/dockerhub-descriptions-updater
    entrypoint: [""]
  variables:
    DOCKERHUB_USERNAME: hmajid2301
    DOCKERHUB_PASSWORD: ${DOCKER_PASSWORD}
    DOCKERHUB_REPO_NAME: composerisation
  script:
    - pandoc --from rst README.rst --to markdown_strict -o README.md
    - node /app/index.js

publish_package:staging:
  stage: pre-publish
  only:
    - /^release/.*$/
  variables:
    PYPI_USERNAME: $PYPI_STAGING_USERNAME
    PYPI_PASSWORD: $PYPI_STAGING_PASSWORD
  script:
    - pip install tox
    - make pypi-check
    - make pypi-upload OPTIONS="-- --repository-url https://test.pypi.org/legacy/"

publish-package:production:
  stage: publish
  only:
    - /^release/.*$/
  variables:
    PYPI_USERNAME: $PYPI_PRODUCTION_USERNAME
    PYPI_PASSWORD: $PYPI_PRODUCTION_PASSWORD
  script:
    - pip install tox
    - make pypi-check
    - make pypi-upload

publish:website:
  stage: publish
  image: ubuntu:18.04
  only:
    - master
  script:
    - apt update && apt install -y curl gnupg2
    - echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    - apt-get update && apt-get install -y google-cloud-sdk
    - cd website
    - cat $APP_ENGINE_DEPLOY_KEY > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project composerisation app deploy
